import mysql from 'mysql2/promise';
import { error } from 'node:console';


// ============================================== //
// STEP 1: IMPORTS AND DATABASE SELECTOR
// ============================================= //

//so we will have a function below that  checks what the user selected in ui dropdown
//eg: sakila or airportdb and grab the matching connection string from .env file
//DATABASE_URL! "I guarantee that this variable is not null or undefined right now, so do not show me an error."
function getDbUrl(dbName?: string) {
    if (dbName === "airportdb")
        return process.env.DATABASE_URL_AIRPORT || process.env.DATABASE_URL!
    if (dbName === "sakila")
        return process.env.DATABASE_URL_SAKILA || process.env.DATABASE_URL!
    //by default it will be sakila db only in dropdown being selected so this is our fallback
    return process.env.DATABASE_URL_SAKILA || process.env.DATABASE_URL!;
}

// ============================================== //
// STEP 2: THE CONNECTION TESTER (testConnection)
// ============================================== //

/*
dbName?: string: Takes an optional database name
 (e.g., 'airportdb' or 'sakila'). 
 It passes this name to our getDbUrl() function 
 from earlier to grab the correct connection 
 string from our .env file.addLog?: (msg: string) => void: Takes an optional callback function. If you pass a function here, it sends the success or error message string back to your frontend UI so the user can see what is happening in real-time.
*/
export async function testConnection(dbName?: string, addLog?: (msg: string) => void) {
    try {

        //open a connection, ping it to test it and immediately close it
        const connection = await mysql.createConnection(getDbUrl(dbName));
        await connection.ping();
        const msg = `success: The database ${dbName} is connected successfully! :)
        `;
        console.log(msg);
        //sends the log back to ui 
        if (addLog) addLog(msg); //show log back to ui

    } catch (error: any) {
        const msg = `
        ERROR: could not connect to ${dbName}. 
        Reason: ${error.message}`//mesage is for native js object error
        console.error(msg); //used errr not log to see it in red color in terminal
        if (addLog) addLog(msg);//show error back to ui
    }
}

// ============================================== //
// STEP 3: Query RUNNER (EXECUTE RAW SQL)
// ============================================== //

/*
This function is the engine that runs the SQL query generated by the AI.

dbName?: string: Tells the function which database to connect to (sakila or airportdb) so it runs the query against the correct tables.
sqlQuery: string: This is the raw SQL query string that gets passed over from your AI prompt (e.g., "SELECT * FROM actor;").
addLog?: (msg: string) => void: Again, this is that optional callback function to send real-time log messages from the backend to your frontend UI.
*/

export async function execute(sql: string, dbName?: string, addLog?: (msg: string) => void) {
    try {
        const msgl = `Executing query on Local MySQL: ${sql}`;
        console.log(msgl);
        if (addLog) addLog(msgl);

        //connect to mysql
        const connection = await mysql.createConnection(getDbUrl(dbName));

        // Executes actual Ai's sql query against your data
        const [rows] = await connection.query(sql);

        //close connection and return the data
        await connection.end();

        const msg2 = `Query successful!`;
        console.log(msg2);
        if (addLog)
            addLog(msg2);

        return rows;
    } catch (error: any) {
        throw new Error(`SQL syntax or execute the error: ${error.message}`);

    }
}

// ===================================================//
// STEP 4: SCHEMA BUILDER (getSchema)
// ==================================================//
/*
This is the most complex and most important function. 
It reads your entire database structure 
and turns it into a giant string so the AI knows what columns exist.
*/
/*
Why we need this: If you ask the AI "Show me all employees",
the AI needs to know if the table is called employees, users, or staff. 
This function scans your database and gives the AI a "map" to look at before 
it writes the query!
*/


/*

NOTE: FOR CLEANING THE DB URL
mysql://root:secretPass@127.0.0.1:3306/sakila?ssl=true
                                       └───┬───┘
                                     .pop() gives this
                                           │
                                     sakila?ssl=true
                                     ───┬── ───┬────
                                      [0]     [1] (after .split("?"))
                                        │
                                     sakila
*/



export async function getSchema(dbName?: string, addLog?: (msg: string) => void) {

    try {
        const dbUrl = getDbUrl(dbName);
        const connection = await mysql.createConnection(dbUrl);

        // 1. get a list of all tables in db
        const [tables]: any = await connection.query(
            "SHOW TABLES;"
        )
        /*
                const actualDbName = dbUrl.split("/").pop()?.split("?")[0];
                if (addLog) {
                    addLog(`Current Database Schema: ${actualDbName}`);
                }
        */
        let schemaStr = "";

        // 2. Loop through each table to grab its schema
        for (const row of tables) {
            const tableName = Object.values(row)[0] as string;

            // 3. Run 'DESCRIBE' to get all the columns for this table
            const [columns]: any = await connection.query(
                `DESCRIBE \`${tableName}\``);

            // 4. Format the columns into a nice string for AI
            const columnDefs = columns.map((col: any) => {

                if (col.Key === "PRI") return `${col.Field} :PK`;
                if (col.Key === "MUL") return `${col.Field} :FK`;
                return col.Field;
            }).join(",");

            schemaStr = schemaStr + `Table:${tableName} (${columnDefs})\n`;

        }
        await connection.end();
        return schemaStr;
    } catch (error: any) {
        return "Error fetching schema. "
    }
}